extends: airbnb
env:
  es6: true
  node: true
  mocha: true
rules:
  max-len: ['error', 120, 4, { ignoreUrls: true, ignoreComments: false, ignoreStrings: true, ignoreTemplateLiterals: true }]
  no-param-reassign: 0