version: '2'
services:
  api:
    image: wow-wings
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:8080"
      - "9080:5858"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USERNAME=app
      - DB_PASSWORD=app
    links:
      - db
  db:
    image: postgres
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
    volumes:
      - ./pgdata:/var/lib/postgresql