version: '2'
services:
  api:
    container_name: api
    image: wow-wings
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:3000"
      - "9080:5858"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USERNAME=app
      - DB_PASSWORD=app
    links:
      - db
  db:
    container_name: db
    image: postgres
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
    volumes:
      - /Users/worapholjanekittanpaiboon/wow_wings_database:/var/lib/postgresql
  redis:
    image: redis
    ports:
      - "6379"
    links:
      - db