version: '2'
services:
  api:
    image: wow-wings
    cpu_shares: 100
    mem_limit: 256000000
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USERNAME=app
      - DB_PASSWORD=app